M48
; DRILL file {KiCad 7.0.10} date Tuesday, January 23, 2024 at 08:12:18 pm
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-23T20:12:18+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X120.78Y-33.43
X120.78Y-39.21
T2
X124.46Y-27.94
X124.46Y-99.06
M30
