M48
; DRILL file {KiCad 7.0.7} date 2024 January 03, Wednesday 09:04:39
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-03T09:04:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X27.647Y-27.647
X27.647Y-27.647
X27.647Y-98.767
X27.647Y-98.767
T0
M30
