;-----------------------------------------------------------------------------
; VARIABLES A..Z
;-----------------------------------------------------------------------------
vars:   .data $+1
        .data 111       ; Variable A 
        .data 2222      ; Variable B
        .data 33333     ; Variable C
        .data 0         ; Variable D
        .data 12        ; Variable E
        .data 0         ; Variable F
        .data 0         ; Variable G
        .data 0         ; Variable H
        .data 0         ; Variable I
        .data 0         ; Variable J
        .data 0         ; Variable K
        .data 0         ; Variable L
        .data 0         ; Variable M
        .data 0         ; Variable N
        .data 0         ; Variable O
        .data 0         ; Variable P
        .data 0         ; Variable Q
        .data 0         ; Variable R
        .data 0         ; Variable S
        .data 0         ; Variable T
        .data 0         ; Variable U
        .data 0         ; Variable V
        .data 0         ; Variable W
        .data 0         ; Variable X
        .data 0         ; Variable Y
        .data 0         ; Variable Z

